# -*- coding: utf-8 -*-
"""dashboard_calories.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10atf1ogsKkbZIbH2XnpfHwuq-c75kBfJ
"""

"""
Dashboard Prediksi Kalori Terbakar
Model Machine Learning untuk estimasi kalori yang terbakar saat olahraga
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import pickle
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Konfigurasi halaman
st.set_page_config(
    page_title="Prediksi Kalori Terbakar",
    page_icon="🔥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main-header {
        text-align: center;
        padding: 1rem;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border-radius: 10px;
        margin-bottom: 2rem;
    }
    .result-card {
        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        border-radius: 15px;
        padding: 1.5rem;
        text-align: center;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    .calorie-number {
        font-size: 3rem;
        font-weight: bold;
        color: #ff6b35;
    }
    .info-box {
        background-color: #f8f9fa;
        border-left: 4px solid #ff6b35;
        padding: 1rem;
        border-radius: 5px;
        margin: 1rem 0;
    }
    .stButton>button {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border: none;
        padding: 0.5rem 2rem;
        font-weight: bold;
    }
    .stButton>button:hover {
        background: linear-gradient(135deg, #5a67d8 0%, #6b46a0 100%);
        color: white;
    }
</style>
""", unsafe_allow_html=True)

# Load model dan preprocessor
@st.cache_resource
def load_model():
    """Load model dan preprocessor yang telah disimpan"""
    try:
        model = joblib.load('best_calorie_model.pkl')
        scaler = joblib.load('scaler.pkl')
        with open('feature_columns.pkl', 'rb') as f:
            features = pickle.load(f)
        return model, scaler, features
    except Exception as e:
        st.error(f"Gagal memuat model: {e}")
        st.info("Pastikan file model (best_calorie_model.pkl, scaler.pkl, feature_columns.pkl) berada di direktori yang sama")
        return None, None, None

# Fungsi untuk menghitung BMR (Basal Metabolic Rate)
def calculate_bmr(weight, height, age, gender):
    """
    Menghitung BMR menggunakan rumus Mifflin-St Jeor
    """
    if gender == "Laki-laki":
        return 10 * weight + 6.25 * height - 5 * age + 5
    else:
        return 10 * weight + 6.25 * height - 5 * age - 161

# Fungsi untuk membuat prediksi
def predict_calories(model, scaler, features, input_data):
    """
    Melakukan prediksi kalori berdasarkan input pengguna
    """
    # Buat DataFrame dari input
    df_input = pd.DataFrame([input_data])

    # Hitung BMR dan fitur interaksi
    df_input['BMR'] = df_input.apply(
        lambda row: calculate_bmr(row['Weight'], row['Height'], row['Age'], row['Gender']),
        axis=1
    )
    df_input['BMR_x_Duration'] = df_input['BMR'] * df_input['Duration']

    # Encoding Gender
    df_input['Gender_male'] = (df_input['Gender'] == "Laki-laki").astype(int)

    # Pilih fitur yang sesuai
    X = df_input[features]

    # Normalisasi fitur numerik
    numeric_features = ['Age', 'Height', 'Weight', 'Duration', 'Heart_Rate',
                        'Body_Temp', 'BMR', 'BMR_x_Duration']
    X[numeric_features] = scaler.transform(X[numeric_features])

    # Prediksi
    prediction = model.predict(X)[0]

    return prediction

# Header
st.markdown("""
<div class="main-header">
    <h1 style="color: white;">🔥 Prediksi Kalori yang Terbakar</h1>
    <p style="color: white; margin-top: -10px;">
    Estimasi kalori yang terbakar berdasarkan data diri dan aktivitas olahraga Anda
    </p>
</div>
""", unsafe_allow_html=True)

# Sidebar untuk input pengguna
with st.sidebar:
    st.image("https://img.icons8.com/fluency/96/000000/heart-health.png", width=80)
    st.markdown("## 📊 Data Diri")

    # Data demografi
    gender = st.radio(
        "**Jenis Kelamin**",
        options=["Laki-laki", "Perempuan"],
        horizontal=True,
        help="Jenis kelamin mempengaruhi BMR dan estimasi kalori"
    )

    age = st.number_input(
        "**Usia (tahun)**",
        min_value=15,
        max_value=100,
        value=30,
        step=1,
        help="Usia dalam tahun (15-100 tahun)"
    )

    col1, col2 = st.columns(2)
    with col1:
        height = st.number_input(
            "**Tinggi Badan (cm)**",
            min_value=100,
            max_value=250,
            value=170,
            step=1,
            help="Tinggi badan dalam sentimeter"
        )
    with col2:
        weight = st.number_input(
            "**Berat Badan (kg)**",
            min_value=30,
            max_value=200,
            value=70,
            step=1,
            help="Berat badan dalam kilogram"
        )

    st.divider()

    st.markdown("## 🏃 Aktivitas Olahraga")

    duration = st.number_input(
        "**Durasi Olahraga (menit)**",
        min_value=1,
        max_value=180,
        value=30,
        step=5,
        help="Durasi berolahraga dalam menit"
    )

    heart_rate = st.number_input(
        "**Denyut Jantung (bpm)**",
        min_value=60,
        max_value=200,
        value=120,
        step=5,
        help="Denyut jantung saat berolahraga (beats per minute)"
    )

    body_temp = st.number_input(
        "**Suhu Tubuh (°C)**",
        min_value=35.0,
        max_value=42.0,
        value=37.5,
        step=0.1,
        format="%.1f",
        help="Suhu tubuh saat berolahraga dalam Celsius"
    )

    st.divider()

    # Tombol prediksi
    predict_button = st.button(
        "🔮 Prediksi Kalori",
        type="primary",
        use_container_width=True
    )

    st.markdown("---")
    st.caption("💡 **Tips:** Gunakan denyut jantung yang diukur saat berolahraga untuk hasil yang lebih akurat")

# Inisialisasi model
model, scaler, features = load_model()
model_loaded = model is not None

# Area utama untuk hasil prediksi
if predict_button and model_loaded:
    # Siapkan input
    input_data = {
        'Age': age,
        'Height': height,
        'Weight': weight,
        'Duration': duration,
        'Heart_Rate': heart_rate,
        'Body_Temp': body_temp,
        'Gender': gender
    }

    # Lakukan prediksi
    with st.spinner("Menghitung prediksi..."):
        prediction = predict_calories(model, scaler, features, input_data)
        bmr = calculate_bmr(weight, height, age, gender)

    # Tampilkan hasil
    st.balloons()

    # Card hasil prediksi
    st.markdown("## 📈 Hasil Prediksi")

    col_result1, col_result2, col_result3 = st.columns(3)

    with col_result1:
        st.markdown(f"""
        <div class="result-card">
            <h3>🔥 Kalori Terbakar</h3>
            <div class="calorie-number">{prediction:.0f} kkal</div>
            <p>Selama {duration} menit olahraga</p>
        </div>
        """, unsafe_allow_html=True)

    with col_result2:
        # Estimasi kalori per jam
        calories_per_hour = (prediction / duration) * 60
        st.markdown(f"""
        <div class="result-card">
            <h3>⚡ Intensitas</h3>
            <div class="calorie-number">{calories_per_hour:.0f} kkal/jam</div>
            <p>Rata-rata per jam</p>
        </div>
        """, unsafe_allow_html=True)

    with col_result3:
        st.markdown(f"""
        <div class="result-card">
            <h3>💪 BMR</h3>
            <div class="calorie-number">{bmr:.0f} kkal/hari</div>
            <p>Kalori istirahat per hari</p>
        </div>
        """, unsafe_allow_html=True)

    # Interpretasi hasil
    st.divider()
    st.markdown("## 📝 Interpretasi Hasil")

    col_interpret1, col_interpret2 = st.columns(2)

    with col_interpret1:
        # Kategori intensitas
        if calories_per_hour < 300:
            intensity = "Ringan"
            intensity_color = "🟢"
            intensity_desc = "Aktivitas ringan seperti jalan santai"
        elif calories_per_hour < 500:
            intensity = "Sedang"
            intensity_color = "🟡"
            intensity_desc = "Aktivitas sedang seperti jogging atau bersepeda santai"
        else:
            intensity = "Tinggi"
            intensity_color = "🔴"
            intensity_desc = "Aktivitas intens seperti lari cepat atau HIIT"

        st.markdown(f"""
        <div class="info-box">
            <b>🏷️ Intensitas Olahraga:</b> {intensity_color} **{intensity}**<br>
            <b>⏱️ Durasi:</b> {duration} menit<br>
            <b>💓 Denyut Jantung:</b> {heart_rate} bpm<br>
            <b>📊 Intensitas:</b> {calories_per_hour:.0f} kkal/jam<br>
            <b>📝 Keterangan:</b> {intensity_desc}
        </div>
        """, unsafe_allow_html=True)

    with col_interpret2:
        # Rekomendasi
        st.markdown("""
        <div class="info-box">
            <b>💡 Rekomendasi:</b><br>
        """, unsafe_allow_html=True)

        if prediction < 100:
            st.info("🏃‍♂️ **Intensitas Rendah**\n\nCoba tingkatkan durasi atau kecepatan untuk hasil optimal.")
        elif prediction < 250:
            st.success("🎯 **Intensitas Sedang**\n\nIdeal untuk menjaga kebugaran dan kesehatan jantung!")
        else:
            st.warning("⚡ **Intensitas Tinggi**\n\nPastikan istirahat cukup, hidrasi yang baik, dan jangan lupa pemanasan & pendinginan.")

        # Tambahan info
        st.caption(f"📌 Estimasi berdasarkan data {gender.lower()} usia {age} tahun")

    # Grafik perbandingan
    st.divider()
    st.markdown("## 📊 Analisis Perbandingan")

    # Data untuk grafik
    categories = ['Kalori (Olahraga)', 'BMR (per hari)', 'Kalori per Jam']
    values = [prediction, bmr, calories_per_hour]

    fig = px.bar(
        x=categories,
        y=values,
        title="Perbandingan Metrik Kalori",
        labels={'x': 'Metrik', 'y': 'Kalori (kkal)'},
        color=categories,
        color_discrete_sequence=px.colors.sequential.Oranges_r,
        text_auto='.0f'
    )
    fig.update_layout(height=450, showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

    # Grafik perbandingan dengan target
    st.markdown("### 🎯 Perbandingan dengan Target")

    target_col1, target_col2, target_col3 = st.columns(3)

    with target_col1:
        # Target kalori per minggu
        weekly_calories = prediction * 5  # Asumsi olahraga 5x seminggu
        st.metric(
            label="📅 Target Mingguan (5x)",
            value=f"{weekly_calories:.0f} kkal",
            delta=f"+{weekly_calories/7700*100:.1f}% lemak",
            delta_color="normal"
        )

    with target_col2:
        # Setara dengan makanan
        equivalent_foods = [
            ("🍚 Nasi putih", 130),
            ("🍞 Roti", 70),
            ("🍎 Apel", 95),
            ("🥚 Telur", 155)
        ]
        food_equiv = prediction / 130  # per porsi nasi
        st.metric(
            label="🍽️ Setara Makanan",
            value=f"{food_equiv:.1f} porsi nasi",
            delta="≈ 130 kkal/porsi"
        )

    with target_col3:
        # Waktu yang dibutuhkan
        st.metric(
            label="⏰ Target Mingguan (500 kkal/hari)",
            value=f"{500/prediction*duration:.0f} menit/hari",
            delta="Untuk bakar 500 kkal"
        )

    # Informasi tambahan
    with st.expander("ℹ️ Tentang Prediksi Ini", expanded=False):
        st.markdown("""
        ### 🤖 Metode Prediksi
        - **Model:** XGBoost Regressor (tuned)
        - **Akurasi Model:** MAE = 1.18 kkal, R² = 0.999
        - **Dataset:** 15,000 sampel data olahraga

        ### 📊 Faktor yang Mempengaruhi Kalori Terbakar
        1. **Durasi Olahraga** ⏱️ - Semakin lama, semakin banyak kalori terbakar
        2. **Denyut Jantung** 💓 - Indikator intensitas latihan
        3. **Berat Badan** ⚖️ - Semakin berat, semakin banyak energi yang dibutuhkan
        4. **Suhu Tubuh** 🌡️ - Meningkat seiring intensitas olahraga

        ### ⚠️ Catatan Penting
        Hasil ini adalah **estimasi** berdasarkan model machine learning.
        Faktor individual seperti metabolisme, kondisi kesehatan, dan jenis olahraga
        dapat mempengaruhi hasil aktual.

        Konsultasikan dengan **profesional kesehatan** atau **pelatih kebugaran**
        untuk program yang sesuai dengan kondisi Anda.
        """)

# Tampilkan informasi default jika belum ada prediksi
else:
    st.markdown("""
    <div style="text-align: center; padding: 2rem; background-color: #f0f2f6; border-radius: 10px;">
        <h3>👈 Masukkan Data Diri</h3>
        <p>Silakan masukkan data diri dan aktivitas olahraga Anda di sidebar,
        lalu klik tombol <strong>"Prediksi Kalori"</strong></p>
    </div>
    """, unsafe_allow_html=True)

    # Tampilkan preview fitur penting
    st.markdown("## 📈 Faktor yang Mempengaruhi Kalori Terbakar")

    # Data feature importance dari model
    feature_importance = {
        'Durasi Olahraga': 0.65,
        'Denyut Jantung': 0.15,
        'Suhu Tubuh': 0.08,
        'Berat Badan': 0.05,
        'Usia': 0.03,
        'Tinggi Badan': 0.02,
        'BMR': 0.01,
        'Gender': 0.01
    }

    fig = px.bar(
        x=list(feature_importance.values()),
        y=list(feature_importance.keys()),
        orientation='h',
        title="Tingkat Pengaruh Fitur terhadap Kalori Terbakar",
        labels={'x': 'Tingkat Pengaruh', 'y': 'Fitur'},
        color=list(feature_importance.values()),
        color_continuous_scale='Oranges',
        text_auto='.0%'
    )
    fig.update_layout(height=400)
    st.plotly_chart(fig, use_container_width=True)

    # Tips kesehatan
    st.markdown("## 💪 Tips Meningkatkan Pembakaran Kalori")

    col_tips = st.columns(3)

    tips_data = [
        ("🏃 Interval Training", "Kombinasikan intensitas tinggi dan rendah untuk hasil maksimal"),
        ("💪 Latihan Kekuatan", "Membangun otot meningkatkan metabolisme basal hingga 15%"),
        ("🔄 Konsistensi", "Lakukan olahraga secara teratur minimal 30 menit/hari"),
        ("💧 Hidrasi", "Minum air yang cukup sebelum, selama, dan setelah olahraga"),
        ("😴 Istirahat", "Pemulihan yang cukup penting untuk hasil optimal"),
        ("📱 Pantau Progress", "Catat perkembangan untuk memotivasi diri")
    ]

    for i, (title, desc) in enumerate(tips_data):
        with col_tips[i % 3]:
            st.markdown(f"""
            <div class="info-box">
                <b>{title}</b><br>
                <small>{desc}</small>
            </div>
            """, unsafe_allow_html=True)

    # Kalkulator BMR
    with st.expander("🧮 Kalkulator BMR (Kalori Istirahat)", expanded=False):
        st.markdown("""
        **BMR (Basal Metabolic Rate)** adalah jumlah kalori yang terbakar saat tubuh dalam keadaan istirahat total.

        **Rumus Mifflin-St Jeor:**
        - **Laki-laki:** 10 × berat(kg) + 6.25 × tinggi(cm) - 5 × usia(tahun) + 5
        - **Perempuan:** 10 × berat(kg) + 6.25 × tinggi(cm) - 5 × usia(tahun) - 161

        **Contoh perhitungan untuk Anda:**
        """)

        demo_gender = st.selectbox("Pilih jenis kelamin untuk demo", ["Laki-laki", "Perempuan"], key="demo_gender")
        demo_weight = st.number_input("Berat badan (kg)", 50, 100, 70, key="demo_weight")
        demo_height = st.number_input("Tinggi badan (cm)", 150, 200, 170, key="demo_height")
        demo_age = st.number_input("Usia (tahun)", 18, 80, 30, key="demo_age")

        demo_bmr = calculate_bmr(demo_weight, demo_height, demo_age, demo_gender)
        st.info(f"💡 **BMR Anda:** {demo_bmr:.0f} kkal/hari")
        st.caption("Ini adalah kalori minimal yang dibutuhkan tubuh untuk fungsi dasar seperti bernafas dan detak jantung.")

# Footer
st.divider()
st.markdown("""
<div style="text-align: center; color: #888; font-size: 0.8rem;">
    <p>© 2024 - Prediksi Kalori Terbakar | Model ML dengan akurasi tinggi | Dikembangkan untuk program kebugaran</p>
    <p>⚠️ Hasil prediksi bersifat estimasi. Konsultasikan dengan profesional kesehatan untuk rekomendasi yang tepat.</p>
</div>
""", unsafe_allow_html=True)